### ISSUE TITLE
TTS reads out image captions at the start

### ISSUE THREAD

**Issue by edent** [csisc/Sawtpedia#1]
(Thanks for this project - I love it!)

I used https://en.wikipedia.org/wiki/Marble_Arch which took me to https://sawtpedia.toolforge.org/link?id=Q845529

That starts by reading out 

> The arch with The Cumberland Hotel, [Great Cumberland Place](https://en.wikipedia.org/wiki/Great_Cumberland_Place) and the trees of [Bryanston Square](https://en.wikipedia.org/wiki/Bryanston_Square) beyond, parts of the [British Regency-architecture](https://en.wikipedia.org/wiki/Regency_architecture) [Portman Estate](https://en.wikipedia.org/wiki/Portman_Estate); the hotel has an access to its Tube station"

Before getting to the useful bit of the article:

> Marble Arch is a 19th-century white [marble](https://en.wikipedia.org/wiki/Marble)-faced [triumphal arch](https://en.wikipedia.org/wiki/Triumphal_arch) in [London](https://en.wikipedia.org/wiki/London), [England](https://en.wikipedia.org/wiki/England).

Is it possible to get the TTS to skip image captions for articles?

**Comment by csisc** [comment]
Yes, I developed a new edition where I used WPTools to get only the lead of a Wikipedia Page.

**Comment by csisc** [comment]
I released the code on GitHub. Please feel free to test it. I will update https://sawtpedia.toolforge.org this Saturday.
